server :backend, :user => 'otlive', :addresses => [
  # otlive-autogenerated match: backend1 template:  '{public}', # {host}
  '46.137.10.123', # backend1
  # otlive-autogenerated end
]
server :load_balancer, :user => 'otlive', :addresses => [
  # otlive-autogenerated match: lbimgnfs template:  '{public}', # {host}
  '46.137.124.172', # lbimgnfs
  # otlive-autogenerated end
]
server :frontend1, :user => 'otlive', :addresses => [
  # otlive-autogenerated match: frontend1 template:  '{public}', # {host}
  '79.125.28.152', # frontend1
  # otlive-autogenerated end
]
server :specialfe, :user => 'otlive', :addresses => [
  # otlive-autogenerated match: specialfe template:  '{public}', # {host}
  '46.137.117.188', # specialfe
  # otlive-autogenerated end
]
server :frontends, :user => 'otlive', :addresses => [
  # otlive-autogenerated match: frontend template:  '{public}', # {host}
  '79.125.28.152', # frontend1
  '46.137.12.120', # frontend2
  '46.51.155.80', # frontend3
  '46.137.11.163', # frontend4
  # otlive-autogenerated end
]

server :special_frontend, :user => 'otlive', :address => "46.137.117.188" 

set :app_dir, '/var/www/otlive'
set :branch, 'otlive_production'

task :update, :servers => [:backend, :load_balancer, :frontends] do
  run <<-EOC
    cd #{app_dir}
    git pull origin #{branch}
  EOC
end

task :install_bundle, :servers => [:frontends] do
  run <<-EOC
    cd #{app_dir}
    bundle install
  EOC
end

task :update_special, :servers => :special_frontend do
  run <<-EOC
    cd /var/www/cmsposter
    git pull origin master
    touch tmp/restart.txt
  EOC
end

task :migrate, :servers => :frontend1 do
  run <<-EOC
    cd #{app_dir}
    rake db:migrate
  EOC
end

task :delayed_job_restart, :servers => :frontends do
  run <<-EOC
    cd #{app_dir}
    ./script/delayed_job restart
  EOC
end

task :backgroup_pub_restart, :servers => :frontend1 do
  run <<-EOC
    cd #{app_dir}
    ./script/background_publish restart
  EOC
end

task :whenever, :servers => :frontend1 do
  run <<-EOC
    cd #{app_dir}
    whenever --update
  EOC
end

task :restart, :servers => :frontends, :parallel => false do
  run "touch #{app_dir}/tmp/restart.txt"
end

task :status, :servers =>  [:backend, :load_balancer, :frontends, :specialfe] do
  run "w | grep average; netstat -nat | grep ESTABLISH | wc -l"
end

