#!/bin/bash

# Lee el hostname que está cargado en la metadata de la instancia EC2 y que tiene el
# siguiente formato: hostname=nombre_del_host
HOSTNAME=`/usr/bin/ec2metadata --user-data | /usr/bin/awk '-F=' '$1 == "hostname" {print $2}'`

# y lo agrega en el /etc/hosts
if [ -n $HOSTNAME ]; then
  echo "127.0.0.1 $HOSTNAME" >> /etc/hosts

  echo $HOSTNAME > /etc/hostname
  /bin/hostname $HOSTNAME
fi

echo Booting $HOSTNAME...

# Genera un /etc/hosts con template para que luego actue ec2-update-local.rb
cat <<EOF > /etc/hosts
127.0.0.1 localhost

# otlive-autogenerated match: . template:{public} {host}.public
# otlive-autogenerated end

# otlive-autogenerated match: . template:{private} {host}.private
# otlive-autogenerated end

EOF

# Actualiza el /etc/hosts con los servidores que están correindo.
/root/scripts/ec2-update-local.rb -l -f -c otlive /etc/hosts

# Actualiza el código de la aplicación
su -m otlive -c "cd /var/www/otlive; git pull origin otlive_production"
[[ -s "/usr/local/rvm/scripts/rvm" ]] && source "/usr/local/rvm/scripts/rvm"  # This loads RVM into a shell session.
cd /var/www/otlive && bundle install

# Finalmente arranca el webserver
/etc/init.d/nginx start

